Repository tcet-opensource/documentation, pull requests merged in 2023-06, with the labels that each got.

#106 Add: Blog - TMAI May'23 Ed
  blog/2023-06-06-tmai-may-23/index.md
  blog/2023-06-06-tmai-may-23/med-palm-dc4977b.png
  blog/2023-06-06-tmai-may-23/photoshop.png
  blog/2023-06-06-tmai-may-23/tmai-may23-poster.png
Labels: blogs

#109 [CHANGES] Added Border in Images
  docs/projects/docs-site/sidebar/adding-items.md
  docs/projects/docs-site/sidebar/multiple-sidebars.md
Labels: documentation, enhancement

#107 [BLOG] TMAI May '23 blog added
  blog/2023-06-06-tmai-may-23/index.md
  blog/2023-06-06-tmai-may-23/med-palm-dc4977b.png
  blog/2023-06-06-tmai-may-23/photoshop.png
  blog/2023-06-06-tmai-may-23/tmai-may23-poster.png
Labels: blogs

#105 [ADDED] T&P Website Documentation Added
  docs/projects/docs-site/navbar/search-bar.mdx
  docs/projects/docs-site/sidebar/adding-items.mdx
  docs/projects/docs-site/sidebar/multiple-sidebars.mdx
  docs/projects/tnp-website/about-tnp-website.mdx
  docs/projects/tnp-website/assets/Astro-logo.jpeg
  docs/projects/tnp-website/assets/Awards.png
  docs/projects/tnp-website/assets/Card.png
  docs/projects/tnp-website/assets/CompanyCard_img.png
  docs/projects/tnp-website/assets/ContactForm_img.png
  docs/projects/tnp-website/assets/Core.png
  docs/projects/tnp-website/assets/Dream.png
  docs/projects/tnp-website/assets/Header.png
  docs/projects/tnp-website/assets/HeroTraining.png
  docs/projects/tnp-website/assets/Hero_img.png
  docs/projects/tnp-website/assets/HugeEvents.png
  docs/projects/tnp-website/assets/MainMenu.png
  docs/projects/tnp-website/assets/Normal.png
  docs/projects/tnp-website/assets/PlacementHero.png
  docs/projects/tnp-website/assets/ProfessionalBodies.png
  docs/projects/tnp-website/assets/ReadMore_img.png
  docs/projects/tnp-website/assets/Staff_img.png
  docs/projects/tnp-website/assets/Strapi-logo.png
  docs/projects/tnp-website/assets/SuperDream.png
  docs/projects/tnp-website/assets/Swipper-logo.png
  docs/projects/tnp-website/assets/Testimonial_img.png
  docs/projects/tnp-website/assets/collapsible.png
  docs/projects/tnp-website/assets/companyCard.png
  docs/projects/tnp-website/assets/hero.png
  docs/projects/tnp-website/assets/heroswiper.png
  docs/projects/tnp-website/assets/industryInteraction.png
  docs/projects/tnp-website/assets/industryhero.png
  docs/projects/tnp-website/assets/objective.png
  docs/projects/tnp-website/assets/tailwind-logo.png
  docs/projects/tnp-website/assets/testimonials.png
  docs/projects/tnp-website/assets/tnp-website.png
  docs/projects/tnp-website/directory-structure.md
  docs/projects/tnp-website/frontend/components/about-us.mdx
  docs/projects/tnp-website/frontend/components/companies.mdx
  docs/projects/tnp-website/frontend/components/components.mdx
  docs/projects/tnp-website/frontend/components/event-page.mdx
  docs/projects/tnp-website/frontend/components/footer.mdx
  docs/projects/tnp-website/frontend/components/header.mdx
  docs/projects/tnp-website/frontend/components/hero.mdx
  docs/projects/tnp-website/frontend/components/industry-interaction.mdx
  docs/projects/tnp-website/frontend/components/internships.mdx
  docs/projects/tnp-website/frontend/components/placed-students.mdx
  docs/projects/tnp-website/frontend/components/placement.mdx
  docs/projects/tnp-website/frontend/components/student-award.mdx
  docs/projects/tnp-website/frontend/components/testimonials.mdx
  docs/projects/tnp-website/frontend/components/top-placed-students.mdx
  docs/projects/tnp-website/frontend/components/top-recruiters.mdx
  docs/projects/tnp-website/frontend/components/training.mdx
  docs/projects/tnp-website/frontend/tech-stacks.mdx
  docs/projects/tnp-website/getting-started.md
  docusaurus.config.js
  sidebars.js
Labels: documentation

#115 [ADDED] T&P Frontend Documentation
  docs/projects/tnp-website/assets/AllStars.png
  docs/projects/tnp-website/assets/Contact.png
  docs/projects/tnp-website/assets/LogoMarquee_img.png
  docs/projects/tnp-website/assets/Map.png
  docs/projects/tnp-website/assets/Navigation.png
  docs/projects/tnp-website/assets/StarPerformers2019.png
  docs/projects/tnp-website/assets/StarPerformers2020.png
  docs/projects/tnp-website/assets/StarPerformers2021.png
  docs/projects/tnp-website/assets/StarPerformers2022.png
  docs/projects/tnp-website/assets/StarPerformers2023.png
  docs/projects/tnp-website/assets/SuperStarPerformers.png
  docs/projects/tnp-website/assets/TopPlacedStudents.png
  docs/projects/tnp-website/assets/footer.png
  docs/projects/tnp-website/frontend/components/about-us.mdx
  docs/projects/tnp-website/frontend/components/footer.mdx
  docs/projects/tnp-website/frontend/components/placed-students.mdx
  docs/projects/tnp-website/frontend/components/top-placed-students.mdx
  docs/projects/tnp-website/frontend/components/top-recruiters.mdx
Labels: documentation

#118 [REMOVED] Unnecessary Components Item in Sidebar
  docs/projects/tnp-website/frontend-components/about-us.mdx
  docs/projects/tnp-website/frontend-components/companies.mdx
  docs/projects/tnp-website/frontend-components/components.mdx
  docs/projects/tnp-website/frontend-components/event-page.mdx
  docs/projects/tnp-website/frontend-components/footer.mdx
  docs/projects/tnp-website/frontend-components/header.mdx
  docs/projects/tnp-website/frontend-components/hero.mdx
  docs/projects/tnp-website/frontend-components/industry-interaction.mdx
  docs/projects/tnp-website/frontend-components/internships.mdx
  docs/projects/tnp-website/frontend-components/placed-students.mdx
  docs/projects/tnp-website/frontend-components/placement.mdx
  docs/projects/tnp-website/frontend-components/student-award.mdx
  docs/projects/tnp-website/frontend-components/tech-stacks.mdx
  docs/projects/tnp-website/frontend-components/testimonials.mdx
  docs/projects/tnp-website/frontend-components/top-placed-students.mdx
  docs/projects/tnp-website/frontend-components/top-recruiters.mdx
  docs/projects/tnp-website/frontend-components/training.mdx
  sidebars.js
Labels: documentation

#154 Added TCET Linux Navbar
  docs/projects/tcet-linux-website/assets/mobilenav.jpg
  docs/projects/tcet-linux-website/assets/navbar.jpg
  docs/projects/tcet-linux-website/frontend-components/navbar.mdx
  package-lock.json
  package.json
Labels: documentation

#153 [UPDATE] Updated Footer Component in FMC
  docs/projects/fmc-website/assets/footer.png
  docs/projects/fmc-website/components/footer.mdx
Labels: documentation

#160 [ADDED] Documentation for TCET Linux Website-Footer
  docs/projects/tcet-linux-website/assets/footer.jpg
  docs/projects/tcet-linux-website/frontend-components/footer.mdx
Labels: documentation

#163 [ADDED] Header_Help_Section
  docs/projects/fmc-website/assets/cycle.png
  docs/projects/fmc-website/assets/tos.png
  docs/projects/fmc-website/components/header-help.mdx
Labels: documentation

#165 [ADDED]added tcet-linux-website installation steps
  docs/projects/tcet-linux-website/assets/set1.jpg
  docs/projects/tcet-linux-website/assets/set2.jpg
  docs/projects/tcet-linux-website/frontend-components/installation-steps.mdx
Labels: documentation

#170 [ADDED] Getting started
  docs/projects/fmc-website/assets/code-runner.png
  docs/projects/fmc-website/assets/live-server.png
  docs/projects/fmc-website/getting-started.mdx
Labels: documentation

#173 [ADDED]added Tl Hero Component Docs
  docs/projects/tcet-linux-website/assets/hero.jpg
  docs/projects/tcet-linux-website/assets/popup.jpg
  docs/projects/tcet-linux-website/frontend-components/hero.mdx
Labels: documentation

#184 136 fmc defining cycles
  docs/projects/fmc-website/assets/pig.png
  docs/projects/fmc-website/components/defining-cycle.mdx
Labels: documentation

#185 [ADDED] Tech Stacks of TL
  docs/projects/tcet-linux-website/assets/Astro-logo.jpeg
  docs/projects/tcet-linux-website/assets/JavaScript.png
  docs/projects/tcet-linux-website/assets/TypeScript.png
  docs/projects/tcet-linux-website/assets/tailwind-logo.png
  docs/projects/tcet-linux-website/frontend-components/tech-stacks.mdx
Labels: enhancement

#187 [ADDED] Tech Stacks
  docs/projects/resume-screener-website/assets/Astro-logo.jpeg
  docs/projects/resume-screener-website/assets/JavaScript.png
  docs/projects/resume-screener-website/assets/TypeScript.png
  docs/projects/resume-screener-website/assets/tailwind-logo.png
  docs/projects/resume-screener-website/frontend-components/tech-stacks.mdx
Labels: enhancement

#188 [ADDED] Tech Stacks of FMC
  docs/projects/fmc-website/assets/JavaScript.png
  docs/projects/fmc-website/assets/css.png
  docs/projects/fmc-website/assets/html.png
  docs/projects/fmc-website/components/tech-stacks.mdx
Labels: documentation, enhancement

#189 [ADDED] TCET Linux Website Documentation
  docs/projects/tcet-linux-website/about-tcet-linux-website.mdx
  docs/projects/tcet-linux-website/assets/Astro-logo.jpeg
  docs/projects/tcet-linux-website/assets/CopyToClipboard.png
  docs/projects/tcet-linux-website/assets/DownloadSection.png
  docs/projects/tcet-linux-website/assets/JavaScript.png
  docs/projects/tcet-linux-website/assets/TypeScript.png
  docs/projects/tcet-linux-website/assets/VerifySection.png
  docs/projects/tcet-linux-website/assets/footer.jpg
  docs/projects/tcet-linux-website/assets/hero.jpg
  docs/projects/tcet-linux-website/assets/mobilenav.jpg
  docs/projects/tcet-linux-website/assets/navbar.jpg
  docs/projects/tcet-linux-website/assets/popup.jpg
  docs/projects/tcet-linux-website/assets/set1.jpg
  docs/projects/tcet-linux-website/assets/set2.jpg
  docs/projects/tcet-linux-website/assets/tailwind-logo.png
  docs/projects/tcet-linux-website/assets/tcet-linux.png
  docs/projects/tcet-linux-website/assets/tos-logo.png
  docs/projects/tcet-linux-website/frontend-components/copy-to-clipboard.mdx
  docs/projects/tcet-linux-website/frontend-components/download-section.mdx
  docs/projects/tcet-linux-website/frontend-components/footer.mdx
  docs/projects/tcet-linux-website/frontend-components/hero.mdx
  docs/projects/tcet-linux-website/frontend-components/installation-steps.mdx
  docs/projects/tcet-linux-website/frontend-components/navbar.mdx
  docs/projects/tcet-linux-website/frontend-components/tech-stacks.mdx
  docs/projects/tcet-linux-website/frontend-components/verify-downloads.mdx
  docs/projects/tcet-linux-website/getting-started.mdx
  sidebars.js
Labels: documentation, enhancement
