Repository tcet-opensource/documentation, pull requests merged in 2023-10, with the labels that each got.

#256 [Added] alias-commands
  docs/projects/tcet-linux/assets/alias-commands.png
  docs/projects/tcet-linux/assets/edit-alias-commands.png
  docs/projects/tcet-linux/guides/alias-commands.md
Labels: hacktoberfest, hacktoberfest-accepted

#272 TL update getting started
  docs/projects/tcet-linux/assets/ApplicationMenu.png
  docs/projects/tcet-linux/assets/Delete&MTTrash.png
  docs/projects/tcet-linux/assets/FileSystem.png
  docs/projects/tcet-linux/assets/Screenshot.png
  docs/projects/tcet-linux/assets/ShutDown.png
  docs/projects/tcet-linux/assets/Trash.png
  docs/projects/tcet-linux/assets/Wallpaper.png
  docs/projects/tcet-linux/assets/manCommand.png
  docs/projects/tcet-linux/assets/neofetch.jpg
  docs/projects/tcet-linux/guides/getting-started.md
Labels: hacktoberfest, hacktoberfest-accepted

#290 All blogs
  blog/2023-10-08-web-crawling/benefits.png
  blog/2023-10-08-web-crawling/index.mdx
  blog/2023-10-08-web-crawling/process.png
  blog/2023-10-08-web-crawling/web_crawl.png
  blog/2023-10-1-cloudgaming/image.png
  blog/2023-10-1-cloudgaming/image2.png
  blog/2023-10-1-cloudgaming/image3.png
  blog/2023-10-1-cloudgaming/index.md
  blog/2023-10-10-CNCF-Zero-to-Merge-Your-first-step-towards-Open-Source/CNCF_Logo.jpg
  blog/2023-10-10-CNCF-Zero-to-Merge-Your-first-step-towards-Open-Source/cncf2.png
  blog/2023-10-10-CNCF-Zero-to-Merge-Your-first-step-towards-Open-Source/index.md
  blog/2023-10-7-Blockchain/BlockChain.jpg
  blog/2023-10-7-Blockchain/Blockchain-Applications.webp
  blog/2023-10-7-Blockchain/Blocks-of-blockchain.png
  blog/2023-10-7-Blockchain/index.md
  src/components/ProjectSection/ProjectPreview.js
Labels: hacktoberfest, hacktoberfest-accepted

#297 241 TL Troubleshoot Welcome App
  docs/projects/tcet-linux/assets/welcome-app.png
  docs/projects/tcet-linux/guides/getting-started.md
  docs/projects/tcet-linux/guides/troubleshoot-app/troubleshoot-welcome-app.md
Labels: hacktoberfest, hacktoberfest-accepted

#302 [ADDED]Added Blog on AI Automation
  blog/2023-10-13-AI-Automation/benefits.png
  blog/2023-10-13-AI-Automation/index.mdx
  blog/2023-10-13-AI-Automation/intro.png
  blog/2023-10-13-AI-Automation/jobs.jpg
  blog/2023-10-13-AI-Automation/nature.png
  blog/authors.yml
  package-lock.json
  package.json
Labels: documentation, blogs, hacktoberfest, hacktoberfest-accepted

#303 [ADDED]Added Blogs on ML Model and Quantum Computing
  blog/2023-10-14-Machine-Learning/end.png
  blog/2023-10-14-Machine-Learning/index.mdx
  blog/2023-10-14-Machine-Learning/intro.png
  blog/2023-10-14-Machine-Learning/process.png
  blog/2023-10-14-Quantum-Computing/comp.png
  blog/2023-10-14-Quantum-Computing/end.png
  blog/2023-10-14-Quantum-Computing/index.mdx
  blog/2023-10-14-Quantum-Computing/intro.png
Labels: documentation, blogs, hacktoberfest

#309 308 tl yay install
  docs/projects/tcet-linux/guides/yay.md
  sidebars.js
Labels: hacktoberfest-accepted

#305 227 TL about tcet linux
  docs/projects/tcet-linux/about-tcet-linux.md
  sidebars.js
Labels: hacktoberfest, hacktoberfest-accepted

#322 [fixed] Updated the icon for 'X' in Footer Section
  docs/about-tcetopensource.mdx
  src/components/Footer/index.js
  static/img/FooterSectionIcons/x.svg
Labels: hacktoberfest, hacktoberfest-accepted

#323 234-contribute-tcet-linux
  docs/projects/tcet-linux/contribute-tcet-linux.md
Labels: hacktoberfest-accepted

#324 Added info in references and credits
  docs/projects/tcet-linux/references-credits.md
Labels: hacktoberfest-accepted

#325 Added variant release info
  docs/projects/tcet-linux/variants-releases.md
Labels: hacktoberfest-accepted
